import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar";
import { AppSidebar } from "@/components/app-sidebar";
import { ClerkProvider , SignedOut } from '@clerk/nextjs';

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
   


<ClerkProvider>
<html lang="en">
  <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
    {/* <header className="flex justify-end items-center p-4 gap-4 h-16"> */}
      <SignedOut>
      </SignedOut>

      <SidebarProvider>
      <AppSidebar />
      <main>
        <SidebarTrigger className="fixed"/>
       {children}
      </main>
    </SidebarProvider>
      
    
  </body>
</html>
</ClerkProvider>
  );
}
